config/routes.rb
Rails.application.routes.draw do

  get "home/workspaceVendors"
  get "home/members"
  get "home/index"
  get "workspace_members/index"
  get "workspace_members/show"
  get "workspace_vendors/index"
  
  root "home#index"

  resources :workspaces
  resources :workspace_members
  resources :workspace_vendors
  resources :vendor_transactions
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/vendor_transaction.rb
class VendorTransaction < ApplicationRecord
  belongs_to :workspace_vendor
end

app/models/workspace.rb
class Workspace < ApplicationRecord
  has_many :workspace_members
  has_many :workspace_vendors

  enum status: {
         active: 0,
         inactive: 1,
       }
end

app/models/workspace_member.rb
class WorkspaceMember < ApplicationRecord
  belongs_to :workspace
  has_person_name
end

app/models/workspace_vendor.rb
class WorkspaceVendor < ApplicationRecord
  belongs_to :workspace
  has_many :vendor_transactions
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    @@workspace = Workspace.first
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @workspace = Workspace.find(1)
  end

  def workspaceVendors
  end

  def members
  end
end

app/controllers/workspace_members_controller.rb
class WorkspaceMembersController < ApplicationController
    def index
        @workspaceMembers = WorkspaceMember.all

        #sort names using first_name alphabetically
        @workspaceMembers = @workspaceMembers.sort_by {|workspaceMember| [workspaceMember.first_name, workspaceMember.created_at]}
    end 

    def show
        @workspaceMember = WorkspaceMember.find(params[:id])
    end


    #create, edit, destroy functions below:
    def new
        @workspaceMember = WorkspaceMember.new
    end

    def create
        @workspaceMember = WorkspaceMember.new(member_params)
        @workspaceMember.workspace_id = 1
        if @workspaceMember.save
            redirect_to workspace_members_path
        else
            render :new
        end
    end

    private

    def member_params
        params.require(:workspace_member).permit(:first_name, :last_name, :email, :title)
    end

end

app/controllers/workspace_vendors_controller.rb
class WorkspaceVendorsController < ApplicationController
    def index
        @workspaceVendors = WorkspaceVendor.where(workspace_id: "1")

        #sort names alphabetically
        @workspaceVendors = @workspaceVendors.sort_by {|workspaceVendor| workspaceVendor.name}
    end

    def show
        @workspaceVendor = WorkspaceVendor.find(params[:id])

        #workspace_vendor_id as a condition
        @vendorTransactions = VendorTransaction.where("workspace_vendor_id = ?", params[:id])
    
    end
end

app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
    def show
        @workspace = Workspace.first
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row">
    <div class="col-6">
        <div class="row">
            <div class="col border-end homeTitle">
                <h1><%= @workspace.name %></h1>
                <p><%= @workspace.domain %></p>
            </div>
        </div>
    </div>

    <div class="col-6">
        <div class="row">
            <div class="col homeLinks">
                <h3><%= link_to "Members", workspace_members_path, class: "homeLink" %></h3>
                <h3><%= link_to "Vendors", workspace_vendors_path, class: "homeLink" %></h3>
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <title>Stackshine Hiring Assessment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

  </head>
  
  <body>
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <%= link_to root_path do %>
          <%= image_tag "https://www.stackshine.com/images/full_logo.svg", class: "logo"%>
        <% end %>
      </div>
    </nav>

    <%= yield %>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  
  </body>
</html>

app/views/workspace_members/index.html.erb
<div class="row main">
  <div class="col-1"></div>
  <div class="col-1 backButton">
    <h3><%= link_to "←Back", root_path, class: "backButton" %></h3>
  </div>
  <div class="col-1"></div>

  <div class="col-6">
    <div class="row">
      <div class="col">
        <h1>Members</h1>
      </div>
    </div>

    <div class="row">
      <div class="col membersTable">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Title</th>
              <th scope="col">Email</th>
            </tr>
          </thead>
          <tbody>
            <% @workspaceMembers.each do |workspaceMember| %>
              <tr>
                <td><%= link_to workspaceMember.name, workspace_member_path(workspaceMember.id), class: "nameLink" %></td>
                <td><%= workspaceMember.title %></td>
                <td><%= workspaceMember.email %></td>
              </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>
    
  <div class="col-3"></div>
</div>

app/views/workspace_members/new.html.erb
<h1>Create a New Member</h1>

<%= form_for @workspaceMember, url: workspace_members_path do |f| %> 
  <p>
  <%= f.label :first_name %>
  <br>
  <%= f.text_field :first_name %>
  </p>

  <p>
  <%= f.label :last_name %>
  <br>
  <%= f.text_field :last_name %>
  </p>

  <p>
  <%= f.label :email %>
  <br>
  <%= f.text_field :email %>
  </p>

  <p>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
  </p>

  <p>
  <%= f.submit %>
  </p>

<% end %>

app/views/workspace_members/show.html.erb
<div class="row main">
  <div class="col-1"></div>
  <div class="col-1 backButton">
    <h3><%= link_to "←Back", workspace_members_path, class: "backButton" %></h3>
  </div>
  <div class="col-1"></div>

  <div class="col-6">
    <div class="row">
      <div class="col">
        <h1><%= @workspaceMember.name %></h1>
      </div>
    </div>

    <div class="row">
      <div class="col memberTable">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">First</th>
              <th scope="col">Last</th>
              <th scope="col">Title</th>
              <th scope="col">Email</th>
              <th scope="col">Start Date</th>
            </tr>
          </thead>
          <tbody>
              <tr>
                <td><%= @workspaceMember.first_name %></td>
                <td><%= @workspaceMember.last_name %></td>
                <td><%= @workspaceMember.title %></td>
                <td><%= @workspaceMember.email %></td>
                <!-- convert to local time and get date only -->
                <td><%= @workspaceMember.created_at.getlocal.to_date %></td>
              </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col-3"></div>
</div>

app/views/workspace_vendors/_vendorTransactions.html.erb
<table class="table transactionsTable">
  <thead>
    <tr>
      <th scope="col">Description</th>
      <th scope="col">Amount($)</th>
      <th scope="col">Date</th>
    </tr>
  </thead>
  <tbody>
    <% @vendorTransactions.each do |vendorTransaction| %>
      <tr>
        <td><%= vendorTransaction.description %></td>
        <!-- conver cents to dollars -->
        <td><%= (vendorTransaction.amount_in_cents / 100).to_s + "." + format('%02d', (vendorTransaction.amount_in_cents % 100).to_s) %></td>
        <!-- convert to local time and get date only -->
        <td><%= vendorTransaction.transaction_date.getlocal.to_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/workspace_vendors/index.html.erb
<div class="row main">
  <div class="col-1"></div>
  <div class="col-1 backButton">
    <h3><%= link_to "←Back", root_path, class: "backButton" %></h3>
  </div>
  <div class="col-1"></div>

  <div class="col-6">
    <div class="row">
      <div class="col">
        <h1>Vendors</h1>
      </div>
    </div>

    <div class="row">
      <div class="col vendorsTable">
        <table class="table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Description</th>
            </tr>
          </thead>
          <tbody>
            <% @workspaceVendors.each do |workspaceVendor| %>
              <tr>
                <td><%= link_to workspaceVendor.name, workspace_vendor_path(workspaceVendor.id), class: "nameLink" %></td>
                <td><%= workspaceVendor.description %></td>
              </tr>
            <% end %>

          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col-3"></div>
</div>

app/views/workspace_vendors/show.html.erb
<div class="row main">
  <div class="col-1"></div>
  <div class="col-1 backButton">
    <h3><%= link_to "←Back", workspace_vendors_path, class: "backButton" %></h3>
  </div>
  <div class="col-1"></div>

  <div class="col-6">
      <div class="row">
        <div class="col">
          <h1><%= @workspaceVendor.name %></h1>
        </div>
      </div>

      <div class="row">
        <div class="col vendorTable">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>

              </tr>
            </thead>
            <tbody>
                <tr>
                  <td><%= @workspaceVendor.name %></td>
                  <td><%= @workspaceVendor.description %></td>
                </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="row marginTop200">
        <div class="col">
          <h4>Transactions:</h4>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <%= render "workspace_vendors/vendorTransactions" %>
        </div>
      </div>

  </div>

  <div class="col-3"></div>
</div>

app/views/workspaces/show.html.erb
<h1>Showing Workspace Details</h1>
<h1><%= @workspace.name %></h1>